# docker/docker-compose.yml
version: '3'

services:
  php-fpm:
    build:
      context: ./app
    volumes:
      - ./app:/var/www
  nginx:
    image: nginx:alpine
    volumes:
      - ./app:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "8000:80"